## Generated SDC file "aes_top.out.sdc"

## Copyright (C) 2019  Intel Corporation. All rights reserved.
## Your use of Intel Corporation's design tools, logic functions 
## and other software and tools, and any partner logic 
## functions, and any output files from any of the foregoing 
## (including device programming or simulation files), and any 
## associated documentation or information are expressly subject 
## to the terms and conditions of the Intel Program License 
## Subscription Agreement, the Intel Quartus Prime License Agreement,
## the Intel FPGA IP License Agreement, or other applicable license
## agreement, including, without limitation, that your use is for
## the sole purpose of programming logic devices manufactured by
## Intel and sold by Intel or its authorized distributors.  Please
## refer to the applicable agreement for further details, at
## https://fpgasoftware.intel.com/eula.


## VENDOR  "Altera"
## PROGRAM "Quartus Prime"
## VERSION "Version 19.1.0 Build 670 09/22/2019 SJ Lite Edition"

## DATE    "Wed May 20 15:11:45 2020"

##
## DEVICE  "5CSXFC6D6F31I7"
##


#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3



#**************************************************************
# Create Clock
#**************************************************************

create_clock -name {altera_reserved_tck} -period 33.333 -waveform { 0.000 16.666 } [get_ports {altera_reserved_tck}]
create_clock -name {XCVR_REFCLK_125} -period 8.000 -waveform { 0.000 4.000 } [get_ports {XCVR_REFCLK_125}]


#**************************************************************
# Create Generated Clock
#**************************************************************



#**************************************************************
# Set Clock Latency
#**************************************************************



#**************************************************************
# Set Clock Uncertainty
#**************************************************************

set_clock_uncertainty -rise_from [get_clocks {altera_reserved_tck}] -rise_to [get_clocks {altera_reserved_tck}] -setup 0.170  
set_clock_uncertainty -rise_from [get_clocks {altera_reserved_tck}] -rise_to [get_clocks {altera_reserved_tck}] -hold 0.060  
set_clock_uncertainty -rise_from [get_clocks {altera_reserved_tck}] -fall_to [get_clocks {altera_reserved_tck}] -setup 0.170  
set_clock_uncertainty -rise_from [get_clocks {altera_reserved_tck}] -fall_to [get_clocks {altera_reserved_tck}] -hold 0.060  
set_clock_uncertainty -fall_from [get_clocks {altera_reserved_tck}] -rise_to [get_clocks {altera_reserved_tck}] -setup 0.170  
set_clock_uncertainty -fall_from [get_clocks {altera_reserved_tck}] -rise_to [get_clocks {altera_reserved_tck}] -hold 0.060  
set_clock_uncertainty -fall_from [get_clocks {altera_reserved_tck}] -fall_to [get_clocks {altera_reserved_tck}] -setup 0.170  
set_clock_uncertainty -fall_from [get_clocks {altera_reserved_tck}] -fall_to [get_clocks {altera_reserved_tck}] -hold 0.060  
set_clock_uncertainty -rise_from [get_clocks {XCVR_REFCLK_125}] -rise_to [get_clocks {XCVR_REFCLK_125}] -setup 0.170  
set_clock_uncertainty -rise_from [get_clocks {XCVR_REFCLK_125}] -rise_to [get_clocks {XCVR_REFCLK_125}] -hold 0.060  
set_clock_uncertainty -rise_from [get_clocks {XCVR_REFCLK_125}] -fall_to [get_clocks {XCVR_REFCLK_125}] -setup 0.170  
set_clock_uncertainty -rise_from [get_clocks {XCVR_REFCLK_125}] -fall_to [get_clocks {XCVR_REFCLK_125}] -hold 0.060  
set_clock_uncertainty -fall_from [get_clocks {XCVR_REFCLK_125}] -rise_to [get_clocks {XCVR_REFCLK_125}] -setup 0.170  
set_clock_uncertainty -fall_from [get_clocks {XCVR_REFCLK_125}] -rise_to [get_clocks {XCVR_REFCLK_125}] -hold 0.060  
set_clock_uncertainty -fall_from [get_clocks {XCVR_REFCLK_125}] -fall_to [get_clocks {XCVR_REFCLK_125}] -setup 0.170  
set_clock_uncertainty -fall_from [get_clocks {XCVR_REFCLK_125}] -fall_to [get_clocks {XCVR_REFCLK_125}] -hold 0.060  


#**************************************************************
# Set Input Delay
#**************************************************************



#**************************************************************
# Set Output Delay
#**************************************************************



#**************************************************************
# Set Clock Groups
#**************************************************************

set_clock_groups -asynchronous -group [get_clocks {altera_reserved_tck}] 


#**************************************************************
# Set False Path
#**************************************************************

set_false_path -to [get_registers {*alt_xcvr_resync*sync_r[0]}]
set_false_path -to [get_keepers {*altera_std_synchronizer:*|din_s1}]
set_false_path -from [get_keepers {altera_reserved_tdi}] -to [get_keepers {pzdyqx*}]
set_false_path -from [get_registers {*altera_jtag_src_crosser:*|sink_data_buffer*}] -to [get_registers {*altera_jtag_src_crosser:*|src_data*}]
set_false_path -from [get_registers {*|altera_tse_register_map:U_REG|command_config[9]}] -to [get_registers {*|altera_tse_mac_tx:U_TX|*}]
set_false_path -from [get_registers {*|altera_tse_register_map:U_REG|mac_0[*]}] -to [get_registers {*|altera_tse_mac_tx:U_TX|*}]
set_false_path -from [get_registers {*|altera_tse_register_map:U_REG|mac_1[*]}] -to [get_registers {*|altera_tse_mac_tx:U_TX|*}]
set_false_path -from [get_registers {*|altera_tse_register_map:U_REG|mac_0[*]}] -to [get_registers {*|altera_tse_mac_rx:U_RX|*}]
set_false_path -from [get_registers {*|altera_tse_register_map:U_REG|mac_1[*]}] -to [get_registers {*|altera_tse_mac_rx:U_RX|*}]
set_false_path -from [get_registers {*|altera_tse_register_map:U_REG|frm_length[*]}] -to [get_registers {*|altera_tse_mac_rx:U_RX|*}]
set_false_path -to [get_pins -nocase -compatibility_mode {*|altera_tse_reset_synchronizer:*|altera_tse_reset_synchronizer_chain*|clrn}]
set_false_path -to [get_pins -nocase -compatibility_mode {*|alt_rst_sync_uq1|altera_reset_synchronizer_int_chain*|clrn}]


#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************

set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_13:TX_STATUS|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_13:TX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_2|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_34:RX_STATUS|wr_g_ptr_reg[*]}] -to [get_registers {*altera_tse_a_fifo_34:RX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_WR_G_PTR|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers *] -to [get_registers {*altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_rx_converter:U_RXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_tx_converter:U_TXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_rx_converter:U_RXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_tx_converter:U_TXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|out_data_buffer[*]}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] 100.000
set_max_delay -from [get_registers *] -to [get_registers {*altera_tse_false_path_marker:*|data_out_reg*}] 100.000


#**************************************************************
# Set Minimum Delay
#**************************************************************

set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_13:TX_STATUS|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_13:TX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_2|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_34:RX_STATUS|wr_g_ptr_reg[*]}] -to [get_registers {*altera_tse_a_fifo_34:RX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_WR_G_PTR|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers *] -to [get_registers {*altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_rx_converter:U_RXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_tx_converter:U_TXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_rx_converter:U_RXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_tx_converter:U_TXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|out_data_buffer[*]}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|in_data_toggle}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|out_data_toggle_flopped}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}] -100.000
set_min_delay -from [get_registers *] -to [get_registers {*altera_tse_false_path_marker:*|data_out_reg*}] -100.000


#**************************************************************
# Set Input Transition
#**************************************************************



#**************************************************************
# Set Net Delay
#**************************************************************

set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*|q}] -to [get_registers {*altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_clock_crosser:*|in_data_toggle|q}] -to [get_registers {*altera_tse_clock_crosser:*|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_clock_crosser:*|out_data_toggle_flopped|q}] -to [get_registers {*altera_tse_clock_crosser:*|altera_eth_tse_std_synchronizer:out_to_in_synchronizer|altera_std_synchronizer_nocut:*|din_s1}]
set_net_delay -max 4.000 -from [get_pins -compatibility_mode {*altera_tse_clock_crosser:*|in_data_buffer[*]|q}] -to [get_registers {*altera_tse_clock_crosser:*|out_data_buffer[*]}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_13:TX_STATUS|altera_tse_gray_cnt:U_WRT|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_13:TX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_2|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_34:RX_STATUS|wr_g_ptr_reg[*]|q}] -to [get_registers {*altera_tse_a_fifo_34:RX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_WR_G_PTR|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_24:*|altera_tse_gray_cnt:U_RD|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*altera_tse_a_fifo_24:*|altera_tse_gray_cnt:U_WRT|g_out[*]|q}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}]
set_net_delay -max 6.000 -from [get_pins -compatibility_mode {*|q}] -to [get_registers {*altera_tse_false_path_marker:*|data_out_reg*}]


#**************************************************************
# Set Max Skew
#**************************************************************

set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_data_tx_clock_crosser|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_tx_counter_cntl:U_TXCNT|altera_tse_clock_crosser:host_convert_addr_tx_clock_crosser|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_data_clock_cross|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_rx_counter_cntl:U_RXCNT|altera_tse_clock_crosser:host_convert_addr_clock_cross|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_11|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_pcs_control:U_REG|altera_tse_mdio_reg:U_REG|altera_tse_clock_crosser:i_partner_ability_clock_crosser|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_10|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_6|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_12|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_8|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|in_data_toggle one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|in_data_buffer[*]}] -to [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|altera_eth_tse_std_synchronizer:in_to_out_synchronizer|altera_std_synchronizer_nocut:*|din_s1 one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_mac_control:U_MAC_CONTROL|altera_tse_register_map:U_REG|altera_tse_clock_crosser:U_SYNC_7|out_data_buffer[*]}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_opt_1246:TX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:TX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_1|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_opt_1246:RX_DATA|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_opt_1246:RX_DATA|altera_eth_tse_std_synchronizer_bundle:U_SYNC_3|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_tx_min_ff:U_TXFF|altera_tse_a_fifo_13:TX_STATUS|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_13:TX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_2|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_mac:i_tse_mac|altera_tse_top_w_fifo_10_100_1000:U_MAC_TOP|altera_tse_top_w_fifo:U_MAC|altera_tse_rx_min_ff:U_RXFF|altera_tse_a_fifo_34:RX_STATUS|wr_g_ptr_reg[*]}] -to [get_registers {*altera_tse_a_fifo_34:RX_STATUS|altera_eth_tse_std_synchronizer_bundle:U_SYNC_WR_G_PTR|altera_eth_tse_std_synchronizer:*|altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_rx_converter:U_RXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_tx_converter:U_TXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_RD|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_rx_converter:U_RXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 7.500 
set_max_skew -from [get_registers {one_mac:i_one_mac|one_mac_eth_net_mac:eth_net_mac|altera_eth_tse_pcs_pma_phyip:i_tse_pcs_0|altera_tse_top_1000_base_x_strx_gx:altera_tse_top_1000_base_x_strx_gx_inst|altera_tse_top_sgmii_strx_gx:U_SGMII|altera_tse_top_tx_converter:U_TXCV|altera_tse_a_fifo_24:U_DSW|altera_tse_gray_cnt:U_WRT|g_out[*]}] -to [get_registers {*altera_tse_a_fifo_24:*altera_std_synchronizer_nocut:*|din_s1*}] 7.500 


#**************************************************************
# Set Disable Timing
#**************************************************************

set_disable_timing -from * -to * [get_cells -hierarchical {VVYU6267_0}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_0}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_1}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_2}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_3}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_4}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_5}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_6}]
set_disable_timing -from * -to * [get_cells -hierarchical {XWCN9723_7}]
set_disable_timing -from * -to * [get_cells -hierarchical {BVXN3148_0}]
