pipeline
{
    agent any

    stages
    {

        stage("Setup Environment")
        {
            steps
            {
                // Gives Premission To Run sh files
                sh(script:"chmod +x ./ci/Second_Module/compile.sh", label: "Premission for Second_Module")
            }
        }
        stage("Build")
        {
            steps
            {
                sh(script:"./ci/Second_Module/compile.sh", label: "Compiling...")
            }
        }
        stage("Run")
        {
            steps
            {
                sh(script:"./ci/Second_Module/second_module", label: "Running...")
            }
        }
    }
    post
    {
        cleanup
        {
            cleanWs()
            deleteDir() /* clean up our workspace */
        }
    }
}