pipeline
{
    agent any

    stages
    {

        stage("Setup Environment")
        {
            steps
            {
                sh """
                    chmod +x ./ci/Top/compile.sh
                    chmod +x ./ci/First_Module/compile.sh
                    chmod +x ./ci/Second_Module/compile.sh
                """
            }
        }
        stage("Build")
        {
            steps
            {
                script
                {
                    cmds = [
                        "Top Module": {
                            stage("Build top module")
                            {
                                sh(script:"./ci/Top/compile.sh", label: "Compiling...")
                            }
                        },
                        "First Module": {
                            stage("Build first module")
                            {
                                sh(script:"./ci/First_Module/compile.sh", label: "Compiling...")
                            }
                        },
                        "Second Module": {
                            stage("Build second module")
                            {
                                sh(script:"./ci/Second_Module/compile.sh", label: "Compiling...")
                            }
                         },
                    ]

                    parallel cmds
                }
            }
        }
        stage("Run")
        {
            steps
            {
                script
                {
                    cmds = [
                        "Top Module" : {
                            stage("Run top module")
                            {
                                sh(script:"./ci/Top/top_module", label: "Running...")
                            }
                        },
                        "First Module" : {
                            stage("Run first module")
                            {
                                sh(script:"./ci/First_Module/first_module", label: "Running...")
                            }
                        },
                        "Second Module" : {
                            stage("Run second module")
                            {
                                sh(script:"./ci/Second_Module/second_module", label: "Running...")
                            }
                        }
                    ]
                    
                    parallel cmds
                }
            }
        }
    }
    post
    {
        cleanup
        {
            cleanWs()
            deleteDir() /* clean up our workspace */
        }
    }
}