pipeline
{
    agent any

    stages
    {

        stage("Setup Environment")
        {
            steps
            {
                // Gives Premission To Run sh files
                sh(script:"chmod +x ./ci/Top/compile.sh", label: "Premission for Top")
                sh(script:"chmod +x ./ci/First_Module/compile.sh", label: "Premission for First_Module")
                sh(script:"chmod +x ./ci/Second_Module/compile.sh", label: "Premission for Second_Module")
            }
        }
        stage("Run All Modules")
        {
            parallel
            {
                stage('Top Module')
                {
                    steps
                    {
                        //load "./ci/Top/loadtest.groovy"
                        build job: 'Top', propagate: true, wait: true
                    }
                }
                stage('First Module')
                {
                    steps
                    {
                        load "./ci/First_Module/loadtest.groovy"
                    }
                }
                stage('Second Module')
                {
                    steps
                    {
                        load "./ci/Second_Module/loadtest.groovy"
                    }
                }
            }
        }
    }
    post
    {
        cleanup
        {
            cleanWs()
            deleteDir() /* clean up our workspace */
        }
    }
}